substitutions:
  _IMAGE_NAME: "asia-northeast1-docker.pkg.dev/$PROJECT_ID/form-sender-runner/dispatcher"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "Dockerfile.dispatcher",
        "-t",
        "${_IMAGE_NAME}:${SHORT_SHA}",
        "-t",
        "${_IMAGE_NAME}:latest",
        "."
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_NAME}:latest"]

images:
  - "${_IMAGE_NAME}:${SHORT_SHA}"
  - "${_IMAGE_NAME}:latest"
