substitutions:
  _IMAGE_NAME: "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/form-sender-runner/dispatcher"
  _SERVICE_NAME: "form-sender-dispatcher"
  _REGION: "asia-northeast1"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "Dockerfile.dispatcher",
        "-t",
        "${_IMAGE_NAME}:${SHORT_SHA}",
        "-t",
        "${_IMAGE_NAME}:latest",
        "."
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_NAME}:${SHORT_SHA}"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_NAME}:latest"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image=${_IMAGE_NAME}:${SHORT_SHA}",
        "--region=${_REGION}",
        "--project=${PROJECT_ID}",
        "--platform=managed",
        "--no-allow-unauthenticated",
        "--quiet"
      ]

images:
  - "${_IMAGE_NAME}:${SHORT_SHA}"
  - "${_IMAGE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
