create table public.batch_request (
  id bigint generated by default as identity not null,
  batch_id text null,
  company_ids text null,
  requested boolean null,
  completed boolean null,
  created_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  constraint batch_request_pkey primary key (id),
  constraint batch_request_id_key unique (id)
) TABLESPACE pg_default;

create index IF not exists idx_batch_request_batch_id on public.batch_request using btree (batch_id) TABLESPACE pg_default;

create index IF not exists idx_batch_requests_batch_id on public.batch_request using btree (batch_id) TABLESPACE pg_default;
