-- job_executions: Cloud Run job execution tracking
create table if not exists public.job_executions (
  id bigint generated by default as identity primary key,
  execution_id text not null,
  job_type text not null default 'form_sender',
  targeting_id bigint not null,
  run_index_base integer not null default 0,
  task_count integer not null default 1,
  parallelism integer not null default 1,
  shards integer not null default 1,
  workers_per_workflow integer not null default 4,
  status text not null check (status in ('queued','running','succeeded','failed','cancelled')) default 'running',
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone null,
  last_error text null,
  metadata jsonb null
);

create unique index if not exists ux_job_executions_execution_id
  on public.job_executions (execution_id);

create index if not exists ix_job_executions_targeting_status
  on public.job_executions (targeting_id, status, started_at);

create index if not exists ix_job_executions_status_started
  on public.job_executions (status, started_at desc);
