-- send_queue_extra: 当日用一時ワークキュー（companies_extra 対応版・毎朝リセット）
create table if not exists public.send_queue_extra (
  id bigint generated by default as identity primary key,
  target_date_jst date not null,
  targeting_id bigint not null,
  company_id bigint not null,
  priority integer not null default 0,
  shard_id integer not null default 0,
  status text not null check (status in ('pending','assigned','done','failed')) default 'pending',
  assigned_by text null,
  assigned_at timestamp with time zone null,
  attempts integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists ux_send_queue_extra_day_target_company
  on public.send_queue_extra (target_date_jst, targeting_id, company_id);

create index if not exists ix_send_queue_extra_claim
  on public.send_queue_extra (target_date_jst, targeting_id, status, shard_id, priority, id);

create index if not exists ix_send_queue_extra_assigned_gc
  on public.send_queue_extra (target_date_jst, targeting_id, status, assigned_at);

