create table public.submissions (
  id bigint generated by default as identity not null,
  targeting_id bigint not null,
  company_id bigint not null,
  error_type text null,
  submitted_at timestamp with time zone null,
  success boolean null,
  constraint submissions_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_submissions_targeting_submitted_success on public.submissions using btree (targeting_id, submitted_at, success) TABLESPACE pg_default;

create index IF not exists idx_submissions_submitted_at on public.submissions using btree (submitted_at) TABLESPACE pg_default;

create index IF not exists idx_submissions_targeting_id_success on public.submissions using btree (targeting_id, success) TABLESPACE pg_default;

create index IF not exists idx_submissions_targeting_id on public.submissions using btree (targeting_id) TABLESPACE pg_default;

create index IF not exists idx_submissions_success on public.submissions using btree (success) TABLESPACE pg_default;

create index IF not exists idx_submissions_targeting_company on public.submissions using btree (targeting_id, company_id, success) TABLESPACE pg_default;
