-- submissions_test: form submission audit table for test mode
create table if not exists public.submissions_test (
  id bigint generated by default as identity not null,
  targeting_id bigint not null,
  company_id bigint not null,
  error_type text null,
  submitted_at timestamp with time zone null,
  success boolean null,
  classify_detail jsonb null,
  field_mapping jsonb null,
  constraint submissions_test_pkey primary key (id)
);

create index if not exists idx_submissions_test_targeting_submitted_success
  on public.submissions_test (targeting_id, submitted_at, success);

create index if not exists idx_submissions_test_submitted_at
  on public.submissions_test (submitted_at);

create index if not exists idx_submissions_test_targeting_id_success
  on public.submissions_test (targeting_id, success);

create index if not exists idx_submissions_test_targeting_id
  on public.submissions_test (targeting_id);

create index if not exists idx_submissions_test_success
  on public.submissions_test (success);

create index if not exists idx_submissions_test_targeting_company
  on public.submissions_test (targeting_id, company_id, success);

create index if not exists idx_submissions_test_target_company_submitted
  on public.submissions_test (targeting_id, company_id, submitted_at);
