name: Codex Review Comment

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  comment-codex-review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed('No pull_request payload');
              return;
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '@codex Review'
            });

